<?php

use Illuminate\Support\Facades\File;

beforeEach(function () {
    $this->root = sys_get_temp_dir().'/learn-sync-assets-'.uniqid();

    File::ensureDirectoryExists("{$this->root}/source/malLatterAtoZsound");
    File::ensureDirectoryExists("{$this->root}/source/latterWordAndSound/audioImage");
    File::ensureDirectoryExists("{$this->root}/source/latterWordAndSound/audioSound");

    // Only "a" and "b" have letter-name clips — the command should skip the rest quietly.
    File::put("{$this->root}/source/malLatterAtoZsound/a.mp3", 'A-SOUND');
    File::put("{$this->root}/source/malLatterAtoZsound/b.mp3", 'B-SOUND');

    // "apple": complete pair. "ant": image only. "axe": sound only (as .wav).
    File::put("{$this->root}/source/latterWordAndSound/audioImage/apple.png", 'APPLE-IMAGE');
    File::put("{$this->root}/source/latterWordAndSound/audioSound/apple.mp3", 'APPLE-SOUND');
    File::put("{$this->root}/source/latterWordAndSound/audioImage/ant.png", 'ANT-IMAGE');
    File::put("{$this->root}/source/latterWordAndSound/audioSound/axe.wav", 'AXE-SOUND');

    $this->lettersOut = "{$this->root}/out/letters/english";
    $this->wordsOut = "{$this->root}/out/words/english";
    $this->dataOut = "{$this->root}/out/words.generated.ts";
});

afterEach(function () {
    File::deleteDirectory($this->root);
});

test('it renames letter-name clips to their spoken-name slug', function () {
    $this->artisan('learn:sync-assets', [
        '--audio-root' => "{$this->root}/source",
        '--letters-out' => $this->lettersOut,
        '--words-out' => $this->wordsOut,
        '--data-out' => $this->dataOut,
    ])->assertExitCode(0);

    expect(File::exists("{$this->lettersOut}/ay.mp3"))->toBeTrue()
        ->and(File::get("{$this->lettersOut}/ay.mp3"))->toBe('A-SOUND')
        ->and(File::exists("{$this->lettersOut}/bee.mp3"))->toBeTrue()
        ->and(File::exists("{$this->root}/source/malLatterAtoZsound/a.mp3"))->toBeFalse();
});

test('it only keeps words that have both an image and a sound, and moves both files', function () {
    $this->artisan('learn:sync-assets', [
        '--audio-root' => "{$this->root}/source",
        '--letters-out' => $this->lettersOut,
        '--words-out' => $this->wordsOut,
        '--data-out' => $this->dataOut,
    ]);

    expect(File::exists("{$this->wordsOut}/apple.png"))->toBeTrue()
        ->and(File::exists("{$this->wordsOut}/apple.mp3"))->toBeTrue()
        ->and(File::exists("{$this->wordsOut}/ant.png"))->toBeFalse()
        ->and(File::exists("{$this->wordsOut}/axe.wav"))->toBeFalse();
});

test('it writes a generated data file grouping complete words by first letter', function () {
    $this->artisan('learn:sync-assets', [
        '--audio-root' => "{$this->root}/source",
        '--letters-out' => $this->lettersOut,
        '--words-out' => $this->wordsOut,
        '--data-out' => $this->dataOut,
    ]);

    $contents = File::get($this->dataOut);

    expect($contents)->toContain('AUTO-GENERATED by `php artisan learn:sync-assets`')
        ->toContain('export const WORDS_BY_LETTER')
        ->toContain('text: "Apple"')
        ->toContain('image: "/audio/words/english/apple.png"')
        ->toContain('audio: "/audio/words/english/apple.mp3"')
        ->not->toContain('text: "Ant"')
        ->not->toContain('text: "Axe"');
});

test('it reports skipped incomplete words without failing', function () {
    $this->artisan('learn:sync-assets', [
        '--audio-root' => "{$this->root}/source",
        '--letters-out' => $this->lettersOut,
        '--words-out' => $this->wordsOut,
        '--data-out' => $this->dataOut,
    ])
        ->expectsOutputToContain('Skipped, image but no sound: ant')
        ->expectsOutputToContain('Skipped, sound but no image: axe')
        ->assertExitCode(0);
});
